"""K-MARIS 품목 분류 마스터 — 대분류 15 + 부품 145.

KTMS_분류전환_마스터통합.xlsx(01·02 시트)에서 뽑아 저장소에 고정한 값이다.
엑셀을 런타임 의존으로 두지 않는다 — 시드는 그 파일이 없는 환경에서도 다시 돌아야 한다.

tree_type: part(EN~HW) · service(TS·TR) · attribute(SB·BU — 트리에 세우지 않는다).
부품 코드는 대분류 코드의 자식이다(EN-001 → EN).
"""
from __future__ import annotations

# 대분류 — 트리 1단. attribute(SB·BU)는 분류가 아니라 속성이라 트리에 세우지 않는다.
MAJORS: list[dict] = [
    {"code": 'EN', "name_en": 'Engines & power systems', "name_ko": '엔진·동력', "tree_type": 'part', "sort": 0, "note": '주기·보조기관, 발전기세트, 추진축계, 시동공기, 연료분사'},
    {"code": 'AU', "name_en": 'Pumps, separation & air', "name_ko": '펌프·분리·공기', "tree_type": 'part', "sort": 1, "note": '펌프, 압축기, 퓨리파이어, 필터류'},
    {"code": 'HT', "name_en": 'Heat transfer, boilers & HVAC', "name_ko": '열교환·보일러·공조', "tree_type": 'part', "sort": 2, "note": '열교환기, 예열기, 보일러, 냉동·공조'},
    {"code": 'VP', "name_en": 'Valves, piping & hydraulics', "name_ko": '밸브·배관·유압', "tree_type": 'part', "sort": 3, "note": '밸브 전종, 액추에이터, 배관 부속, 유압'},
    {"code": 'DK', "name_en": 'Deck, cargo & mooring', "name_ko": '갑판·화물·계류', "tree_type": 'part', "sort": 4, "note": '크레인, 윈치, 계선, 화물, 조타'},
    {"code": 'EA', "name_en": 'Electrical & automation', "name_ko": '전기·자동화', "tree_type": 'part', "sort": 5, "note": '배전, 전동기, 제어, 센서, 케이블, 조명'},
    {"code": 'EV', "name_en": 'Environmental & treatment', "name_ko": '환경·처리', "tree_type": 'part', "sort": 6, "note": 'BWTS, SCR, 스크러버, OWS, STP, 소각기'},
    {"code": 'SB', "name_en": 'Shipbuilding & drydock supply', "name_ko": '신조·도크 납품', "tree_type": 'attribute', "sort": 7, "note": '★품목군이 아닌 공급채널 — 속성 전환 검토'},
    {"code": 'BU', "name_en": 'Bunkering & marine lubricants', "name_ko": '벙커링·윤활유', "tree_type": 'attribute', "sort": 8, "note": '★품목군이 아닌 상품라인 — 속성 전환 검토'},
    {"code": 'TS', "name_en": 'Technical service coordination', "name_ko": '기술서비스', "tree_type": 'service', "sort": 9, "note": '입회, 검사, 수리, 인건·출장'},
    {"code": 'TR', "name_en": 'Trading & delivery support', "name_ko": '트레이딩·납품지원', "tree_type": 'service', "sort": 10, "note": '운송, 통관, 서류, RFQ 취합'},
    {"code": 'SF', "name_en": 'Safety, life saving & fire fighting', "name_ko": '안전·구명·소방', "tree_type": 'part', "sort": 11, "note": 'LSA, FFA, 가스검지 — 현행 체계에 자리 없음'},
    {"code": 'NC', "name_en": 'Navigation & communication', "name_ko": '항해·통신', "tree_type": 'part', "sort": 12, "note": '레이더, GMDSS, 자이로 — 현재 EA에 눌려 있음'},
    {"code": 'AO', "name_en": 'Accommodation & outfitting', "name_ko": '거주구·의장', "tree_type": 'part', "sort": 13, "note": '수밀문, 방화문, 갤리, 사다리·통로'},
    {"code": 'HW', "name_en": 'Hardware & fasteners', "name_ko": '체결류·표준품', "tree_type": 'part', "sort": 14, "note": '볼트, 리테이닝링, 표준 베어링 (119건 매핑에서 도출)'},
]

# 부품 — 트리 2단. major 는 위 MAJORS 의 code.
PARTS: list[dict] = [
    {"code": 'EN-001', "major": 'EN', "group": '연료분사', "name_en": 'Fuel Injector / Fuel Valve', "name_ko": '연료분사밸브(인젝터)', "hs_code": '8409.99', "sort": 0},
    {"code": 'EN-002', "major": 'EN', "group": '연료분사', "name_en": 'Nozzle / Nozzle Tip', "name_ko": '노즐 / 노즐 팁', "hs_code": '8409.99', "sort": 1},
    {"code": 'EN-003', "major": 'EN', "group": '연료분사', "name_en": 'Fuel Injection Pump', "name_ko": '연료분사펌프', "hs_code": '8413.30', "sort": 2},
    {"code": 'EN-004', "major": 'EN', "group": '연료분사', "name_en": 'Plunger & Barrel', "name_ko": '플런저 & 배럴', "hs_code": '8413.91', "sort": 3},
    {"code": 'EN-005', "major": 'EN', "group": '연료분사', "name_en": 'Delivery Valve', "name_ko": '딜리버리 밸브', "hs_code": '8409.99', "sort": 4},
    {"code": 'EN-006', "major": 'EN', "group": '연료분사', "name_en": 'HP Fuel Pipe', "name_ko": '고압 연료관', "hs_code": '8409.99', "sort": 5},
    {"code": 'EN-007', "major": 'EN', "group": '연료분사', "name_en": 'Puncture Valve', "name_ko": '퍽처 밸브', "hs_code": '8409.99', "sort": 6},
    {"code": 'EN-008', "major": 'EN', "group": '실린더', "name_en": 'Cylinder Cover / Head', "name_ko": '실린더 커버', "hs_code": '8409.99', "sort": 7},
    {"code": 'EN-009', "major": 'EN', "group": '실린더', "name_en": 'Cylinder Liner', "name_ko": '실린더 라이너', "hs_code": '8409.99', "sort": 8},
    {"code": 'EN-010', "major": 'EN', "group": '실린더', "name_en": 'Piston / Piston Crown', "name_ko": '피스톤 / 피스톤 크라운', "hs_code": '8409.99', "sort": 9},
    {"code": 'EN-011', "major": 'EN', "group": '실린더', "name_en": 'Piston Ring', "name_ko": '피스톤링', "hs_code": '8409.99', "sort": 10},
    {"code": 'EN-012', "major": 'EN', "group": '실린더', "name_en": 'Piston Rod / Stuffing Box', "name_ko": '피스톤 로드 / 스터핑 박스', "hs_code": '8409.99', "sort": 11},
    {"code": 'EN-013', "major": 'EN', "group": '실린더', "name_en": 'Exhaust Valve & Seat', "name_ko": '배기밸브 / 시트', "hs_code": '8409.99', "sort": 12},
    {"code": 'EN-014', "major": 'EN', "group": '실린더', "name_en": 'Inlet Valve', "name_ko": '흡기밸브', "hs_code": '8409.99', "sort": 13},
    {"code": 'EN-015', "major": 'EN', "group": '실린더', "name_en": 'Cylinder Lubricator', "name_ko": '실린더 주유기', "hs_code": '8413.50', "sort": 14},
    {"code": 'EN-016', "major": 'EN', "group": '운동부', "name_en": 'Connecting Rod', "name_ko": '연접봉', "hs_code": '8409.99', "sort": 15},
    {"code": 'EN-017', "major": 'EN', "group": '운동부', "name_en": 'Crosshead / Guide', "name_ko": '크로스헤드 / 가이드', "hs_code": '8409.99', "sort": 16},
    {"code": 'EN-018', "major": 'EN', "group": '운동부', "name_en": 'Main Bearing', "name_ko": '메인 베어링', "hs_code": '8483.30', "sort": 17},
    {"code": 'EN-019', "major": 'EN', "group": '운동부', "name_en": 'Crankpin Bearing', "name_ko": '크랭크핀 베어링', "hs_code": '8483.30', "sort": 18},
    {"code": 'EN-020', "major": 'EN', "group": '운동부', "name_en": 'Camshaft / Cam', "name_ko": '캠샤프트 / 캠', "hs_code": '8483.10', "sort": 19},
    {"code": 'EN-021', "major": 'EN', "group": '운동부', "name_en": 'Vibration Damper', "name_ko": '진동 댐퍼', "hs_code": '8483.90', "sort": 20},
    {"code": 'EN-022', "major": 'EN', "group": '과급', "name_en": 'Turbocharger Rotor / Cartridge', "name_ko": '터보차저 로터 / 카트리지', "hs_code": '8414.90', "sort": 21},
    {"code": 'EN-023', "major": 'EN', "group": '과급', "name_en": 'Turbocharger Bearing & Seal', "name_ko": '터보차저 베어링 / 씰', "hs_code": '8414.90', "sort": 22},
    {"code": 'EN-024', "major": 'EN', "group": '과급', "name_en": 'Charge Air Cooler', "name_ko": '소기 공기 냉각기', "hs_code": '8419.50', "sort": 23},
    {"code": 'EN-025', "major": 'EN', "group": '시동공기', "name_en": 'Main Starting Valve', "name_ko": '주 시동밸브', "hs_code": '8481.80', "sort": 24},
    {"code": 'EN-026', "major": 'EN', "group": '시동공기', "name_en": 'Starting Air Non-Return Valve', "name_ko": '시동공기 역지밸브', "hs_code": '8481.30', "sort": 25},
    {"code": 'EN-027', "major": 'EN', "group": '시동공기', "name_en": 'Starting Air Distributor', "name_ko": '시동공기 분배기', "hs_code": '8481.80', "sort": 26},
    {"code": 'EN-028', "major": 'EN', "group": '시동공기', "name_en": 'Cylinder Starting Valve', "name_ko": '실린더 시동밸브', "hs_code": '8481.80', "sort": 27},
    {"code": 'EN-029', "major": 'EN', "group": '시동공기', "name_en": 'Slow Turning Valve', "name_ko": '슬로우 터닝 밸브', "hs_code": '8481.80', "sort": 28},
    {"code": 'EN-030', "major": 'EN', "group": '시동공기', "name_en": 'Turning Gear', "name_ko": '터닝 기어', "hs_code": '8483.40', "sort": 29},
    {"code": 'EN-031', "major": 'EN', "group": '제어', "name_en": 'Governor / Actuator', "name_ko": '거버너 / 액추에이터', "hs_code": '8479.89', "sort": 30},
    {"code": 'EN-032', "major": 'EN', "group": '제어', "name_en": 'Cylinder Safety Valve', "name_ko": '안전밸브(실린더)', "hs_code": '8481.40', "sort": 31},
    {"code": 'EN-033', "major": 'EN', "group": '발전', "name_en": 'Main / Emergency Generator', "name_ko": '주발전기 / 비상발전기', "hs_code": '8501.64', "sort": 32},
    {"code": 'EN-034', "major": 'EN', "group": '발전', "name_en": 'Shaft Generator', "name_ko": '축발전기', "hs_code": '8501.64', "sort": 33},
    {"code": 'EN-035', "major": 'EN', "group": '추진', "name_en": 'Propeller / Blade', "name_ko": '프로펠러 / 블레이드', "hs_code": '8487.10', "sort": 34},
    {"code": 'EN-036', "major": 'EN', "group": '추진', "name_en": 'Propeller Shaft / Intermediate Shaft', "name_ko": '프로펠러 축 / 중간축', "hs_code": '8483.10', "sort": 35},
    {"code": 'EN-037', "major": 'EN', "group": '추진', "name_en": 'Stern Tube Seal & Bearing', "name_ko": '선미관 씰 / 베어링', "hs_code": '8484.90', "sort": 36},
    {"code": 'EN-038', "major": 'EN', "group": '추진', "name_en": 'Side / Bow Thruster', "name_ko": '사이드 스러스터', "hs_code": '8487.10', "sort": 37},
    {"code": 'AU-001', "major": 'AU', "group": '펌프', "name_en": 'Centrifugal Pump', "name_ko": '원심펌프', "hs_code": '8413.70', "sort": 38},
    {"code": 'AU-002', "major": 'AU', "group": '펌프', "name_en": 'Screw / Gear Pump', "name_ko": '스크류 / 기어펌프', "hs_code": '8413.60', "sort": 39},
    {"code": 'AU-003', "major": 'AU', "group": '펌프', "name_en": 'Pump Mechanical Seal', "name_ko": '펌프 메커니컬 씰', "hs_code": '8484.20', "sort": 40},
    {"code": 'AU-004', "major": 'AU', "group": '펌프', "name_en": 'Impeller / Wear Ring', "name_ko": '펌프 임펠러 / 웨어링', "hs_code": '8413.91', "sort": 41},
    {"code": 'AU-005', "major": 'AU', "group": '펌프', "name_en": 'Pump Shaft & Bearing', "name_ko": '펌프 샤프트 / 베어링', "hs_code": '8413.91', "sort": 42},
    {"code": 'AU-006', "major": 'AU', "group": '압축기', "name_en": 'Main Air Compressor', "name_ko": '주 공기압축기', "hs_code": '8414.80', "sort": 43},
    {"code": 'AU-007', "major": 'AU', "group": '압축기', "name_en": 'Compressor Valve / Ring Plate', "name_ko": '압축기 밸브 / 링플레이트', "hs_code": '8414.90', "sort": 44},
    {"code": 'AU-008', "major": 'AU', "group": '압축기', "name_en": 'Compressor Piston & Ring', "name_ko": '압축기 피스톤 / 링', "hs_code": '8414.90', "sort": 45},
    {"code": 'AU-009', "major": 'AU', "group": '압축기', "name_en": 'Air Receiver & Fittings', "name_ko": '공기 리시버 / 부속', "hs_code": '7311.00', "sort": 46},
    {"code": 'AU-010', "major": 'AU', "group": '압축기', "name_en": 'Air Dryer', "name_ko": '에어 드라이어', "hs_code": '8479.89', "sort": 47},
    {"code": 'AU-011', "major": 'AU', "group": '청정기', "name_en": 'Oil Purifier / Separator', "name_ko": '유청정기(퓨리파이어)', "hs_code": '8421.19', "sort": 48},
    {"code": 'AU-012', "major": 'AU', "group": '청정기', "name_en": 'Bowl & Disc Set', "name_ko": '퓨리파이어 보울 / 디스크', "hs_code": '8421.99', "sort": 49},
    {"code": 'AU-013', "major": 'AU', "group": '청정기', "name_en": 'Purifier Gear & Bearing', "name_ko": '청정기 기어 / 베어링', "hs_code": '8421.99', "sort": 50},
    {"code": 'AU-014', "major": 'AU', "group": '여과', "name_en": 'FO Filter Element', "name_ko": '연료유 필터 엘리먼트', "hs_code": '8421.23', "sort": 51},
    {"code": 'AU-015', "major": 'AU', "group": '여과', "name_en": 'LO Filter Element', "name_ko": '윤활유 필터 엘리먼트', "hs_code": '8421.23', "sort": 52},
    {"code": 'AU-016', "major": 'AU', "group": '여과', "name_en": 'Air Filter Element', "name_ko": '공기 필터 엘리먼트', "hs_code": '8421.31', "sort": 53},
    {"code": 'AU-017', "major": 'AU', "group": '여과', "name_en": 'Strainer & Basket', "name_ko": '스트레이너 / 바스켓', "hs_code": '8421.29', "sort": 54},
    {"code": 'AU-018', "major": 'AU', "group": '여과', "name_en": 'Auto Backflushing Filter', "name_ko": '자동역세필터', "hs_code": '8421.29', "sort": 55},
    {"code": 'HT-001', "major": 'HT', "group": '열교환', "name_en": 'Plate Heat Exchanger & Plates', "name_ko": '판형 열교환기 / 플레이트', "hs_code": '8419.50', "sort": 56},
    {"code": 'HT-002', "major": 'HT', "group": '열교환', "name_en": 'Shell & Tube Cooler / Tube Bundle', "name_ko": '셸앤튜브 쿨러 / 튜브번들', "hs_code": '8419.50', "sort": 57},
    {"code": 'HT-003', "major": 'HT', "group": '열교환', "name_en": 'Heat Exchanger Gasket', "name_ko": '열교환기 개스킷', "hs_code": '4016.93', "sort": 58},
    {"code": 'HT-004', "major": 'HT', "group": '가열', "name_en": 'FO Heater / Preheater', "name_ko": '연료유 예열기', "hs_code": '8419.89', "sort": 59},
    {"code": 'HT-005', "major": 'HT', "group": '가열', "name_en": 'Electric Heater / Tracing', "name_ko": '전기 히터 / 열선', "hs_code": '8516.80', "sort": 60},
    {"code": 'HT-006', "major": 'HT', "group": '보일러', "name_en": 'Boiler Burner & Nozzle', "name_ko": '보일러 버너 / 노즐', "hs_code": '8416.10', "sort": 61},
    {"code": 'HT-007', "major": 'HT', "group": '보일러', "name_en": 'Boiler Tube', "name_ko": '보일러 수관 / 튜브', "hs_code": '7304.51', "sort": 62},
    {"code": 'HT-008', "major": 'HT', "group": '보일러', "name_en": 'Boiler Safety Valve', "name_ko": '안전밸브(보일러)', "hs_code": '8481.40', "sort": 63},
    {"code": 'HT-009', "major": 'HT', "group": '보일러', "name_en": 'Soot Blower', "name_ko": '수트 블로워', "hs_code": '8424.89', "sort": 64},
    {"code": 'HT-010', "major": 'HT', "group": '보일러', "name_en": 'Economizer / EGB', "name_ko": '이코노마이저 / 배기가스보일러', "hs_code": '8402.12', "sort": 65},
    {"code": 'HT-011', "major": 'HT', "group": '공조냉동', "name_en": 'Refrigeration Compressor', "name_ko": '냉동 압축기', "hs_code": '8414.30', "sort": 66},
    {"code": 'HT-012', "major": 'HT', "group": '공조냉동', "name_en": 'Air Handling Unit', "name_ko": '공조기 / AHU', "hs_code": '8415.82', "sort": 67},
    {"code": 'HT-013', "major": 'HT', "group": '공조냉동', "name_en": 'Blower / Fan', "name_ko": '송풍기 / 팬', "hs_code": '8414.59', "sort": 68},
    {"code": 'VP-001', "major": 'VP', "group": '밸브', "name_en": 'Ball Valve', "name_ko": '볼 밸브', "hs_code": '8481.80', "sort": 69},
    {"code": 'VP-002', "major": 'VP', "group": '밸브', "name_en": 'Butterfly Valve', "name_ko": '버터플라이 밸브', "hs_code": '8481.80', "sort": 70},
    {"code": 'VP-003', "major": 'VP', "group": '밸브', "name_en": 'Globe Valve', "name_ko": '글로브 밸브', "hs_code": '8481.80', "sort": 71},
    {"code": 'VP-004', "major": 'VP', "group": '밸브', "name_en": 'Gate Valve', "name_ko": '게이트 밸브', "hs_code": '8481.80', "sort": 72},
    {"code": 'VP-005', "major": 'VP', "group": '밸브', "name_en": 'Non-Return / Check Valve', "name_ko": '역지밸브(체크/NRV)', "hs_code": '8481.30', "sort": 73},
    {"code": 'VP-006', "major": 'VP', "group": '밸브', "name_en": 'Safety / Relief Valve', "name_ko": '안전밸브 / 릴리프 밸브', "hs_code": '8481.40', "sort": 74},
    {"code": 'VP-007', "major": 'VP', "group": '밸브', "name_en": 'Pressure Reducing Valve', "name_ko": '감압밸브', "hs_code": '8481.10', "sort": 75},
    {"code": 'VP-008', "major": 'VP', "group": '밸브', "name_en": 'Control Valve', "name_ko": '제어밸브', "hs_code": '8481.80', "sort": 76},
    {"code": 'VP-009', "major": 'VP', "group": '밸브', "name_en": 'Solenoid Valve', "name_ko": '솔레노이드 밸브', "hs_code": '8481.80', "sort": 77},
    {"code": 'VP-010', "major": 'VP', "group": '밸브', "name_en": 'Air Vent Head', "name_ko": '공기변 헤드', "hs_code": '8481.80', "sort": 78},
    {"code": 'VP-011', "major": 'VP', "group": '밸브 부속', "name_en": 'Valve Actuator', "name_ko": '밸브 액추에이터(공압/유압/전동)', "hs_code": '8481.90', "sort": 79},
    {"code": 'VP-012', "major": 'VP', "group": '밸브 부속', "name_en": 'Valve Seat & Disc', "name_ko": '밸브 시트 / 디스크', "hs_code": '8481.90', "sort": 80},
    {"code": 'VP-013', "major": 'VP', "group": '밸브 부속', "name_en": 'Valve Stem & Gland', "name_ko": '밸브 스템 / 글랜드', "hs_code": '8481.90', "sort": 81},
    {"code": 'VP-014', "major": 'VP', "group": '밸브 부속', "name_en": 'Valve Repair / Seal Kit', "name_ko": '밸브 오버홀 킷', "hs_code": '8481.90', "sort": 82},
    {"code": 'VP-015', "major": 'VP', "group": '배관', "name_en": 'Pipe & Tube', "name_ko": '파이프 / 튜브', "hs_code": '7304.xx', "sort": 83},
    {"code": 'VP-016', "major": 'VP', "group": '배관', "name_en": 'Flange', "name_ko": '플랜지', "hs_code": '7307.21', "sort": 84},
    {"code": 'VP-017', "major": 'VP', "group": '배관', "name_en": 'Elbow / Tee / Reducer', "name_ko": '엘보 / 티 / 리듀서', "hs_code": '7307.93', "sort": 85},
    {"code": 'VP-018', "major": 'VP', "group": '배관', "name_en": 'Expansion Joint / Bellows', "name_ko": '익스팬션 조인트 / 벨로우즈', "hs_code": '8484.90', "sort": 86},
    {"code": 'VP-019', "major": 'VP', "group": '배관', "name_en": 'Hose & Coupling', "name_ko": '호스 / 커플링', "hs_code": '4009.xx', "sort": 87},
    {"code": 'VP-020', "major": 'VP', "group": '배관', "name_en": 'Gasket / O-Ring / Packing', "name_ko": '개스킷 / O링 / 패킹', "hs_code": '4016.93', "sort": 88},
    {"code": 'VP-021', "major": 'VP', "group": '유압', "name_en": 'Hydraulic Power Pack / Pump', "name_ko": '유압 파워팩 / 펌프', "hs_code": '8412.21', "sort": 89},
    {"code": 'VP-022', "major": 'VP', "group": '유압', "name_en": 'Hydraulic Cylinder', "name_ko": '유압 실린더', "hs_code": '8412.21', "sort": 90},
    {"code": 'VP-023', "major": 'VP', "group": '유압', "name_en": 'Hydraulic Valve Block', "name_ko": '유압 밸브 블록', "hs_code": '8481.20', "sort": 91},
    {"code": 'EA-001', "major": 'EA', "group": '배전', "name_en": 'Main / Distribution Switchboard', "name_ko": '주배전반 / 분전반', "hs_code": '8537.10', "sort": 92},
    {"code": 'EA-002', "major": 'EA', "group": '배전', "name_en": 'Circuit Breaker', "name_ko": '차단기 / ACB / MCCB', "hs_code": '8536.20', "sort": 93},
    {"code": 'EA-003', "major": 'EA', "group": '배전', "name_en": 'Transformer', "name_ko": '변압기', "hs_code": '8504.31', "sort": 94},
    {"code": 'EA-004', "major": 'EA', "group": '전동', "name_en": 'Electric Motor', "name_ko": '전동기', "hs_code": '8501.52', "sort": 95},
    {"code": 'EA-005', "major": 'EA', "group": '전동', "name_en": 'Starter / VFD', "name_ko": '기동기 / 인버터(VFD)', "hs_code": '8504.40', "sort": 96},
    {"code": 'EA-006', "major": 'EA', "group": '전원', "name_en": 'Battery & Charger', "name_ko": '축전지 / 충전기', "hs_code": '8507.20', "sort": 97},
    {"code": 'EA-007', "major": 'EA', "group": '제어', "name_en": 'PLC / Controller', "name_ko": 'PLC / 컨트롤러', "hs_code": '8537.10', "sort": 98},
    {"code": 'EA-008', "major": 'EA', "group": '제어', "name_en": 'Sensor (Pressure/Temp/Level)', "name_ko": '계측 센서(압력·온도·레벨)', "hs_code": '9026.xx', "sort": 99},
    {"code": 'EA-009', "major": 'EA', "group": '제어', "name_en": 'Relay & Contactor', "name_ko": '릴레이 / 접점', "hs_code": '8536.41', "sort": 100},
    {"code": 'EA-010', "major": 'EA', "group": '케이블', "name_en": 'Marine Cable & Gland', "name_ko": '선박용 케이블 / 글랜드', "hs_code": '8544.xx', "sort": 101},
    {"code": 'EA-011', "major": 'EA', "group": '조명', "name_en": 'Marine Light Fitting', "name_ko": '선박용 등기구 / 투광등', "hs_code": '9405.xx', "sort": 102},
    {"code": 'EV-001', "major": 'EV', "group": '평형수', "name_en": 'BWTS Unit', "name_ko": 'BWTS 본체 / 유닛', "hs_code": '8421.21', "sort": 103},
    {"code": 'EV-002', "major": 'EV', "group": '평형수', "name_en": 'UV Lamp & Sleeve', "name_ko": 'UV 램프 / 슬리브', "hs_code": '8539.49', "sort": 104},
    {"code": 'EV-003', "major": 'EV', "group": '평형수', "name_en": 'BWTS Filter Element', "name_ko": 'BWTS 필터 엘리먼트', "hs_code": '8421.29', "sort": 105},
    {"code": 'EV-004', "major": 'EV', "group": '배기', "name_en": 'SCR Catalyst & Module', "name_ko": 'SCR 촉매 / 모듈', "hs_code": '3815.19', "sort": 106},
    {"code": 'EV-005', "major": 'EV', "group": '배기', "name_en": 'Urea Dosing Unit', "name_ko": '요소수 분사 / 도징 유닛', "hs_code": '8424.89', "sort": 107},
    {"code": 'EV-006', "major": 'EV', "group": '배기', "name_en": 'Scrubber Nozzle & Demister', "name_ko": '스크러버 노즐 / 데미스터', "hs_code": '8421.39', "sort": 108},
    {"code": 'EV-007', "major": 'EV', "group": '배기', "name_en": 'EGR Blower & Cooler', "name_ko": 'EGR 블로워 / 쿨러', "hs_code": '8414.80', "sort": 109},
    {"code": 'EV-008', "major": 'EV', "group": '오염방지', "name_en": 'OWS & Element', "name_ko": '유수분리기(OWS) / 엘리먼트', "hs_code": '8421.21', "sort": 110},
    {"code": 'EV-009', "major": 'EV', "group": '오염방지', "name_en": 'Oil Content Meter', "name_ko": '유분농도계(15ppm 알람)', "hs_code": '9027.81', "sort": 111},
    {"code": 'EV-010', "major": 'EV', "group": '오염방지', "name_en": 'Sewage Treatment Plant', "name_ko": '오수처리장치(STP)', "hs_code": '8421.21', "sort": 112},
    {"code": 'EV-011', "major": 'EV', "group": '오염방지', "name_en": 'Incinerator & Burner', "name_ko": '소각기 / 버너', "hs_code": '8417.80', "sort": 113},
    {"code": 'DK-001', "major": 'DK', "group": '계선', "name_en": 'Windlass / Mooring Winch', "name_ko": '윈드라스 / 무어링 윈치', "hs_code": '8425.31', "sort": 114},
    {"code": 'DK-002', "major": 'DK', "group": '계선', "name_en": 'Anchor & Chain', "name_ko": '앵커 / 앵커체인', "hs_code": '7316.00', "sort": 115},
    {"code": 'DK-003', "major": 'DK', "group": '계선', "name_en": 'Capstan / Roller / Fairlead', "name_ko": '캡스턴 / 롤러 / 페어리드', "hs_code": '8425.39', "sort": 116},
    {"code": 'DK-004', "major": 'DK', "group": '하역', "name_en": 'Deck Crane / Hoist', "name_ko": '데크 크레인 / 호이스트', "hs_code": '8426.19', "sort": 117},
    {"code": 'DK-005', "major": 'DK', "group": '하역', "name_en": 'Wire Rope', "name_ko": '크레인 와이어로프', "hs_code": '7312.10', "sort": 118},
    {"code": 'DK-006', "major": 'DK', "group": '하역', "name_en": 'Crane Hydraulic / Slewing Parts', "name_ko": '크레인 유압·슬루잉 부품', "hs_code": '8431.49', "sort": 119},
    {"code": 'DK-007', "major": 'DK', "group": '화물', "name_en": 'Hatch Cover & Packing', "name_ko": '해치커버 / 클리트 / 패킹', "hs_code": '7308.90', "sort": 120},
    {"code": 'DK-008', "major": 'DK', "group": '화물', "name_en": 'Cargo Pump / Loading Arm', "name_ko": '화물창 펌프 / 로딩암', "hs_code": '8413.70', "sort": 121},
    {"code": 'DK-009', "major": 'DK', "group": '조타', "name_en": 'Steering Gear & Hydraulic Unit', "name_ko": '조타기 / 유압 유닛', "hs_code": '8479.89', "sort": 122},
    {"code": 'DK-010', "major": 'DK', "group": '조타', "name_en": 'Rudder Stock / Bearing / Bush', "name_ko": '러더 스톡 / 베어링 / 부싱', "hs_code": '8487.10', "sort": 123},
    {"code": 'SF-001', "major": 'SF', "group": '소방', "name_en": 'Extinguisher / Hose / Nozzle', "name_ko": '소화기 / 소화호스 / 노즐', "hs_code": '8424.10', "sort": 124},
    {"code": 'SF-002', "major": 'SF', "group": '소방', "name_en": 'CO2 Cylinder & Release Valve', "name_ko": 'CO2 실린더 / 방출밸브', "hs_code": '8424.10', "sort": 125},
    {"code": 'SF-003', "major": 'SF', "group": '소방', "name_en": 'Fire Detector & Panel', "name_ko": '화재탐지기 / 경보반', "hs_code": '8531.10', "sort": 126},
    {"code": 'SF-004', "major": 'SF', "group": '소방', "name_en": 'Gas Detector / Flame Arrester', "name_ko": '가스검지기 / 화염방지기', "hs_code": '9027.10', "sort": 127},
    {"code": 'SF-005', "major": 'SF', "group": '구명', "name_en": 'Liferaft / Lifeboat', "name_ko": '구명뗏목 / 구명정', "hs_code": '8906.90', "sort": 128},
    {"code": 'SF-006', "major": 'SF', "group": '구명', "name_en": 'Davit / Launching Appliance / Hook', "name_ko": '다빗 / 진수장치 / 후크', "hs_code": '8425.19', "sort": 129},
    {"code": 'SF-007', "major": 'SF', "group": '구명', "name_en": 'Lifejacket / Lifebuoy / Immersion Suit', "name_ko": '구명동의 / 구명부환 / 이멀전슈트', "hs_code": '6307.20', "sort": 130},
    {"code": 'SF-008', "major": 'SF', "group": '구명', "name_en": 'EPIRB / SART / Pyrotechnics', "name_ko": 'EPIRB / SART / 조난신호', "hs_code": '8526.91', "sort": 131},
    {"code": 'EN-039', "major": 'EN', "group": '연료분사', "name_en": 'Control Rack', "name_ko": '컨트롤 랙', "hs_code": '8409.99', "sort": 132},
    {"code": 'EN-040', "major": 'EN', "group": '연료분사', "name_en": 'Control Sleeve', "name_ko": '컨트롤 슬리브', "hs_code": '8409.99', "sort": 133},
    {"code": 'EN-041', "major": 'EN', "group": '연료분사', "name_en": 'Injection Pump Spring & Seat', "name_ko": '분사펌프 스프링 & 시트', "hs_code": '8409.99', "sort": 134},
    {"code": 'EN-042', "major": 'EN', "group": '연료분사', "name_en": 'Fuel Stop Air Cylinder', "name_ko": '연료차단 에어실린더', "hs_code": '8412.31', "sort": 135},
    {"code": 'EN-043', "major": 'EN', "group": '발전', "name_en": 'Generator Bearing (DE/NDE)', "name_ko": '발전기 베어링(DE/NDE)', "hs_code": '8483.30', "sort": 136},
    {"code": 'EN-044', "major": 'EN', "group": '발전', "name_en": 'Generator Winding & Insulation', "name_ko": '발전기 권선 / 절연물', "hs_code": '8503.00', "sort": 137},
    {"code": 'EN-045', "major": 'EN', "group": '발전', "name_en": 'Generator Frame & End Shield', "name_ko": '발전기 프레임 / 엔드실드', "hs_code": '8503.00', "sort": 138},
    {"code": 'DK-011', "major": 'DK', "group": '하역', "name_en": 'Sheave & Pulley', "name_ko": '시브 / 풀리', "hs_code": '8483.50', "sort": 139},
    {"code": 'DK-012', "major": 'DK', "group": '하역', "name_en": 'Crane Pin & Bush', "name_ko": '크레인 핀 / 부싱', "hs_code": '8431.49', "sort": 140},
    {"code": 'VP-024', "major": 'VP', "group": '유압', "name_en": 'Hydraulic Motor', "name_ko": '유압 모터', "hs_code": '8412.29', "sort": 141},
    {"code": 'HW-001', "major": 'HW', "group": '체결류', "name_en": 'Bolt, Nut & Washer', "name_ko": '볼트 / 너트 / 와셔', "hs_code": '7318.15', "sort": 142},
    {"code": 'HW-002', "major": 'HW', "group": '체결류', "name_en": 'Retaining Ring, Key & Pin', "name_ko": '리테이닝링 / 키 / 핀', "hs_code": '7318.29', "sort": 143},
    {"code": 'HW-003', "major": 'HW', "group": '표준품', "name_en": 'Standard Bearing', "name_ko": '표준 베어링', "hs_code": '8482.10', "sort": 144},
]
