"""Parse vendor quote response files (PDF/Excel) to extract filled-in price data.

Supports the KTMS Vendor Quotation Request Sheet format (generated by vendor_xlsx.py)
and similar tabular formats where the vendor has filled in:
  Unit Price (USD), Lead Time, Country of Origin, Manufacturer, Technical Remarks
"""
from __future__ import annotations
import io
from typing import Any, Dict, List, Optional


# Ordered by specificity — more specific keywords first to avoid partial collisions
# e.g. "unit price" must be checked before "unit"
_HEADER_KEYWORDS: Dict[str, List[str]] = {
    "item_no":      ["no.", "no"],
    "part_no":      ["part no"],
    "description":  ["description"],
    "qty":          ["qty"],
    "cost_price":   ["unit price", "price (usd)", "price(usd)", "unit_price"],
    "unit":         ["unit"],
    "lead_time":    ["lead time", "lead_time"],
    "origin":       ["country of origin", "country\nof origin", "country", "origin"],
    "manufacturer": ["manufacturer"],
    "remark":       ["technical remarks", "remarks / alternatives",
                     "alternatives", "remark"],
}


def _match_col(header: str) -> Optional[str]:
    """Return field name for a column header string, or None."""
    h = header.lower().replace("\n", " ").strip()
    for field, keywords in _HEADER_KEYWORDS.items():
        if any(kw in h for kw in keywords):
            return field
    return None


def _make_col_map(header_row: List[Any]) -> Dict[str, int]:
    """Build {field: 0-based-column-index} from a header row."""
    col_map: Dict[str, int] = {}
    for j, cell in enumerate(header_row):
        field = _match_col(str(cell or ""))
        if field and field not in col_map:
            col_map[field] = j
    return col_map


def _safe_float(val: Any) -> Optional[float]:
    if val is None or str(val).strip() in ("", "-", "—"):
        return None
    try:
        return float(str(val).replace(",", "").strip())
    except ValueError:
        return None


def _is_data_row(row: List[Any], item_no_col: int) -> bool:
    """Return True if the first-column value is a numeric item number."""
    if item_no_col >= len(row):
        return False
    try:
        int(float(str(row[item_no_col] or "").strip()))
        return True
    except (ValueError, TypeError):
        return False


# ── Excel parser ──────────────────────────────────────────────────────────────

def _parse_excel(file_bytes: bytes) -> List[Dict]:
    import openpyxl
    wb = openpyxl.load_workbook(io.BytesIO(file_bytes), data_only=True)
    ws = wb.active

    # Find header row: must contain "part no" AND at least one vendor-fill column
    header_row_idx: Optional[int] = None
    for r in range(1, min(ws.max_row + 1, 30)):
        row_text = " ".join(
            str(ws.cell(r, c).value or "").lower() for c in range(1, 15)
        )
        if "part no" in row_text and (
            "unit price" in row_text or "lead time" in row_text
        ):
            header_row_idx = r
            break

    if header_row_idx is None:
        return []

    headers = [
        ws.cell(header_row_idx, c).value
        for c in range(1, ws.max_column + 1)
    ]
    col_map = _make_col_map(headers)
    item_no_col = col_map.get("item_no", 0)
    part_no_col = col_map.get("part_no", 1)

    items: List[Dict] = []
    for r in range(header_row_idx + 1, ws.max_row + 1):
        row = [ws.cell(r, c).value for c in range(1, ws.max_column + 1)]

        if not _is_data_row(row, item_no_col):
            continue
        if part_no_col < len(row) and not row[part_no_col]:
            continue

        item: Dict[str, Any] = {}
        for field, j in col_map.items():
            val = row[j] if j < len(row) else None
            item[field] = str(val or "").strip()

        if "cost_price" in item:
            f = _safe_float(item["cost_price"])
            item["cost_price"] = f if f is not None else ""

        items.append(item)

    return items


# ── PDF parser ────────────────────────────────────────────────────────────────

def _parse_pdf(file_bytes: bytes) -> List[Dict]:
    import pdfplumber

    items: List[Dict] = []

    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        col_map: Dict[str, int] = {}

        for page in pdf.pages:
            tables = page.extract_tables() or []
            for table in tables:
                if not table or len(table) < 2:
                    continue

                # Locate header row
                header_idx: Optional[int] = None
                for i, row in enumerate(table):
                    row_text = " ".join(str(c or "").lower() for c in row)
                    if "part no" in row_text and (
                        "unit price" in row_text or "lead time" in row_text
                    ):
                        header_idx = i
                        break

                if header_idx is not None:
                    col_map = _make_col_map(table[header_idx])

                if not col_map:
                    continue

                item_no_col = col_map.get("item_no", 0)
                for row in table[header_idx + 1 if header_idx is not None else 0 :]:
                    if not row or not any(c for c in row):
                        continue
                    if not _is_data_row(row, item_no_col):
                        continue

                    item: Dict[str, Any] = {}
                    for field, j in col_map.items():
                        val = row[j] if j < len(row) else ""
                        item[field] = str(val or "").strip()

                    if "cost_price" in item:
                        f = _safe_float(item["cost_price"])
                        item["cost_price"] = f if f is not None else ""

                    if item.get("part_no"):
                        items.append(item)

    return items


# ── Public API ────────────────────────────────────────────────────────────────

def parse_vendor_quote_bytes(file_bytes: bytes, filename: str = "") -> List[Dict]:
    """Parse vendor quote response from raw bytes.

    Returns a list of dicts with keys matching the VendorQuote item columns:
      item_no, part_no, cost_price, lead_time, origin, manufacturer, remark
    """
    name = filename.lower()
    if name.endswith((".xlsx", ".xls")):
        return _parse_excel(file_bytes)
    if name.endswith(".pdf"):
        return _parse_pdf(file_bytes)

    # Unknown extension — try Excel first, then PDF
    try:
        result = _parse_excel(file_bytes)
        if result:
            return result
    except Exception:
        pass
    return _parse_pdf(file_bytes)
