"""공급역량 카탈로그(Supply Capability)의 손으로 적은 판단들.

DB 가 답하지 못하는 것만 여기 둔다 — 나머지(누가 무엇을 견적했고 발주됐는가)는
build_supply_capability.py 가 매번 DB 에서 다시 센다.

1. MAKER_ALIASES   : 문서·메일에 흔들려 적힌 메이커 이름 → 명부(makers.name) 이름
2. DISPLAY_NAMES   : 고객에게 보일 이름(명부 표기에 오타·법인 꼬리가 붙은 것)
3. DEAL_EVIDENCE   : 딜 한 건이 어느 메이커의 어느 부품이었나. 줄의 maker·category_id
                     칸이 대부분 비어 있어서, 제목·줄 내용을 읽고 사람이 짚어 둔 것이다.
4. PROPOSED_TAGS   : 명부에 분류가 비어 있는 메이커의 분류 제안(사람이 확정 전).
5. SERVICE_RECORDS : 기술 서비스(TS) 실적 — 부품 트리에 자리가 없어 따로 적는다.
"""

# 문서·메일 표기 → 명부 이름. 키는 대문자로 비교한다.
MAKER_ALIASES = {
    "HYUNDAI HEAVY INDUSTRIES CO., LTD. (HHI)": "HYUNDAI Heavy Industries",
    "HYUNDAI HEAVY INDUSTRIES CO., LTD.": "HYUNDAI Heavy Industries",
    "HYUNDAI HEAVY INDUSTRIES": "HYUNDAI Heavy Industries",
    "HHI": "HYUNDAI Heavy Industries",
    "HIMSEN": "HYUNDAI Heavy Industries",
    "HYUNDAI-B&W": "HYUNDAI Heavy Industries",
    "HYUNDAI B&W": "HYUNDAI Heavy Industries",
    "MAN B&W": "Everllence B&W",
    "MAN-B&W": "Everllence B&W",
    "MAN ENERGY SOLUTIONS": "Everllence B&W",
    "NAKAKITA SEISAKUSHO": "NAKAKITA SEISAKOSHO",
    "NAKAKITA": "NAKAKITA SEISAKOSHO",
    "AALBORG INDUSTRIES": "AALBORG",
    "SHIN SHIN MACHINERY CO., LTD.": "SHINSHIN MACHINERY",
    "SHIN SHIN MACHINERY": "SHINSHIN MACHINERY",
    "SHINSHIN": "SHINSHIN MACHINERY",
    "MACGREGOR": "MacGregor",
    "ORIENTAL": "Oriental P&E",
    "SANGSANGIN": "SANGSSANGIN Ship Machinery",
    "HANSUNGHOLDINGS CO., LTD.": "Hansung Heavy Industries",
    "HANSUNG": "Hansung Heavy Industries",
    "TYCO FIRE & SECURITY": "Johnson Controls",
    "TYCO": "Johnson Controls",
    "DAIHATSU ENGINE": "DAIHATSU",
    "SIEMENS DI KOREA": "SIEMENS",
    "EAGLE BURGMANN": "EagleBurgmann",
    # 명부 안의 중복(같은 회사가 두 이름으로 올라 있음)
    "HANSUNGMC": "Hansung Heavy Industries",
}

# 명부에 없는 메이커 — 견적·요청 줄에만 이름이 나온 곳. (이름, 본국)
EXTRA_MAKERS = {
    "PRETECH": "Korea",
    "SCANIA": "Sweden",
    "Stamford": "United Kingdom",
    "ZEXEL": "Japan",
    "OMEGA": "",
    "KOMECO": "Korea",
    "YUMYUNG": "Korea",
    "Murrelektronik": "Germany",
    "Cryostar": "France",
}

# 고객에게 보일 이름. 없으면 명부 이름 그대로.
DISPLAY_NAMES = {
    "AKASAKA enigine": "Akasaka",
    "NIIGATA enigine": "Niigata",
    "DAIHATSU": "Daihatsu",
    "Atlas Copco Korea": "Atlas Copco",
    "Emerson Process Management Korea": "Emerson",
    "Kelvion Heat Exchangers (China)": "Kelvion",
    "L'Orange Fuel Injection Trading (Suzhou)": "L'Orange",
    "Ingersoll-Rand Machinery (Shanghai)": "Ingersoll Rand",
    "HYUNDAI Heavy Industries": "HD Hyundai (HiMSEN / Hyundai-B&W)",
    "Everllence B&W": "Everllence (MAN B&W)",
    "NAKAKITA SEISAKOSHO": "Nakakita",
    "SHINSHIN MACHINERY": "Shinshin Machinery",
    "SANGSSANGIN Ship Machinery": "Sangsangin",
    "Hansung Heavy Industries": "Hansung",
    "HANSUNGmc": "Hansung",
    "CSSC Marine Power Zhenjiang(ZJMD)": "CSSC Zhenjiang (ZJMD)",
    "CSSC Engine(CSE)": "CSSC Engine (CSE)",
    "HITACHI Zosen Marine Engine": "Hitachi Zosen",
    "HYUNDAI MARINE MACHINERY": "Hyundai Marine Machinery",
    "Wuhan Marine Machinery Plant": "Wuhan Marine Machinery",
    "Mitsubishi Kakoki Kaisha": "Mitsubishi Kakoki",
    "Shaanxi Diesel Heavy Industry": "Shaanxi Diesel",
    "Chongqing Hongjiang Machinery": "Chongqing Hongjiang",
    "SaierNico Electric & Automation": "SaierNico",
    "Rolls-Royce Marine": "Rolls-Royce Marine (Kongsberg)",
    "Mt.H Control Valves": "Mt.H Control Valves",
    "KANGRIM HEAVY INDUSTRIES": "Kangrim",
    "YANMAR": "Yanmar",
    "PARKER": "Parker",
    "SIEMENS": "Siemens",
    "XYLEM": "Xylem",
    "GRUNDFOS": "Grundfos",
    "DESMI": "Desmi",
    "FRAMO": "Framo",
    "AALBORG": "Aalborg",
    "VIKING ENGINEERING": "Viking Engineering",
    "PANASIA": "Panasia",
    "KORVAL": "Korval",
    "STX Engine": "STX Engine",
    "Doosan Engine": "Doosan Engine (HD Hyundai Marine Engine)",
    "DAEYANG ELECTRIC": "Daeyang Electric",
    "DONGHWA ENTEC": "Donghwa Entec",
    "HANLA IMS": "Hanla IMS",
    "CEPHAS PIPELINES": "Cephas Pipelines",
    "HMMCO": "HMMCO",
    "Hübner": "Hübner",
    "ACE VALVE": "ACE Valve", "DONG EUN VALVE": "Dong Eun Valve", "HANYANG VALVE": "Hanyang Valve",
    "SEJIN VALVE": "Sejin Valve", "WONKWANG VALVE": "Wonkwang Valve", "S&S VALVE": "S&S Valve",
    "PK VALVE": "PK Valve", "DKC VALVE": "DKC Valve", "KOREA KEYSTON VALVE": "Korea Keyston Valve",
    "NEWAY": "Neway", "KEYSTONE": "Keystone", "HANSHIN ELECTRONICS": "Hanshin Electronics",
    "HERIANA": "Heriana", "JOKWANG ILI": "Jokwang ILI", "KUMKANG": "Kumkang", "KWANG SAN": "Kwang San",
    "SAMGONG": "Samgong", "SAMJOO ENG": "Samjoo Eng.", "SAMKUN CENTURY": "Samkun Century",
    "B-I INDUSTRIAL": "B-I Industrial", "B.Y. CONTROLS": "B.Y. Controls", "G.S HIGH-TECHER": "G.S High-Techer",
    "YOOWON INDUSTRIES": "Yoowon Industries", "PRETECH": "Pretech", "OMEGA": "Omega", "KOMECO": "Komeco",
    "YUMYUNG": "Yumyung", "SCANIA": "Scania", "SCANA": "Scana", "K.C. LTD": "K.C. Ltd.", "LUXCO": "Luxco",
    "HI AIR KOREA": "Hi Air Korea", "MESON": "Meson", "S&SYS": "S&SYS", "DK-LOK": "DK-Lok",
}

# 딜 한 건 = (rfq_id) → [(메이커 또는 None, [부품 코드], 등급 덮어쓰기 또는 None)].
# 등급을 비우면 그 딜의 근거 등급(발주 A · 견적 B · RFQ C)을 그대로 쓴다.
# 한 딜에 견적을 받은 줄과 못 받은 줄이 섞이면 줄 묶음마다 등급을 적는다(56번).
DEAL_EVIDENCE = {
    1:  [(None, ["VP-020"], None)],   # 라이너 O-ring 교체 서비스 — 라이너를 댄 것은 아니다
    6:  [(None, ["AU-001", "AU-003", "AU-004", "AU-005", "VP-020", "HW-003"], None)],
    8:  [("HYUNDAI Heavy Industries", ["AU-001", "AU-002"], None)],
    9:  [("SCANIA", ["EN-033"], None), ("Stamford", ["EN-033"], None)],
    10: [(None, ["SF-006", "VP-024"], None)],
    11: [("HYUNDAI Heavy Industries", ["EN-003", "EN-004", "EN-039", "EN-040", "EN-041", "EN-042", "HW-001", "HW-002"], None)],
    12: [("HYUNDAI Heavy Industries", ["EN-003", "EN-004"], None)],
    13: [("SANGSSANGIN Ship Machinery", ["DK-004", "DK-006", "VP-014", "VP-023", "VP-024"], None)],
    16: [("HYUNDAI Heavy Industries", ["EN-003", "EN-004", "EN-039", "EN-040", "EN-041", "EN-042"], None),
         ("PRETECH", ["EN-003", "EN-004", "EN-040", "EN-041"], None)],
    17: [("HYUNDAI Heavy Industries", ["VP-021"], None)],
    18: [("CSSC Marine Power Zhenjiang(ZJMD)", ["EN-018", "EN-016"], None)],
    19: [("Oriental P&E", ["SF-006", "EA-011"], None)],
    20: [(None, ["EN-025", "VP-001", "VP-011", "VP-014"], None)],
    21: [("KORVAL", ["EN-025", "VP-014", "AU-016"], None)],
    22: [("HYUNDAI Heavy Industries", ["EA-008"], None)],
    23: [(None, ["EA-009"], None)],
    24: [(None, ["SF-004"], None)],
    25: [(None, ["VP-005"], None)],
    26: [(None, ["AU-001"], None)],
    27: [("YANMAR", ["VP-019"], None)],
    28: [(None, ["DK-004"], None)],
    29: [(None, ["EN-006"], None)],
    30: [("HYUNDAI Heavy Industries", ["EN-025", "VP-014", "VP-020", "EA-009"], None)],
    31: [("SIEMENS", ["VP-008", "VP-011"], None)],
    32: [(None, ["DK-004", "VP-022"], None)],
    33: [("HYUNDAI Heavy Industries", ["EA-007"], None), ("KOMECO", ["EA-007"], None)],
    34: [("Everllence B&W", ["EN-025", "VP-001", "VP-011", "VP-014"], None),
         ("Mt.H Control Valves", ["EN-025", "VP-001", "VP-011", "VP-014"], None)],
    35: [("Oriental P&E", ["DK-004", "EA-010"], None)],
    36: [("YUMYUNG", ["EA-007"], None)],
    37: [("Murrelektronik", ["EA-008", "EA-009"], None)],
    38: [("Everllence B&W", ["EN-006"], None), ("Doosan Engine", ["EN-006"], None)],
    39: [("Oriental P&E", ["DK-004", "DK-006", "VP-019", "VP-020"], None)],
    40: [("MacGregor", ["DK-011"], None)],
    41: [("PARKER", ["EA-008"], None)],
    42: [("Honeywell", ["EA-008"], None)],
    43: [("HYUNDAI Heavy Industries", ["EN-025", "EN-026", "EN-029"], None)],
    44: [("HYUNDAI Heavy Industries", ["EA-007"], None), ("KOMECO", ["EA-007"], None)],
    45: [("YANMAR", ["EN-001", "EN-008", "EN-009", "EN-010", "EN-011", "EN-013", "EN-014", "EN-018",
                     "EN-019", "EN-023", "AU-003", "AU-004", "AU-014", "AU-015", "VP-020", "HW-003"], None)],
    46: [(None, ["EA-001", "EA-002"], None)],
    47: [("HYUNDAI Heavy Industries", ["VP-018", "HW-001", "EN-023", "EN-010", "EN-031", "AU-002",
                                       "EA-007", "EN-021"], None)],
    48: [("SHINSHIN MACHINERY", ["AU-001"], None)],
    49: [("WinGD", ["VP-001"], None)],
    50: [("Hansung Heavy Industries", ["EN-043", "EN-044", "EN-045"], None)],
    51: [("NAKAKITA SEISAKOSHO", ["VP-002", "VP-011", "VP-013", "VP-014", "VP-020"], None)],
    52: [(None, ["EA-009"], None)],
    53: [("ZEXEL", ["EN-031"], None), ("DAIHATSU", ["EN-031"], None)],
    54: [(None, ["EV-009"], None)],
    55: [("HYUNDAI Heavy Industries", ["EA-009", "EA-001"], None)],
    56: [("YANMAR", ["EN-031", "EA-004", "EA-008"], "B"),
         ("AALBORG", ["HT-006"], "B"),
         ("Johnson Controls", ["SF-003"], "B"),
         ("DESMI", ["AU-003"], "B"),
         ("EagleBurgmann", ["AU-003"], "B"),
         ("Danfoss", ["EA-008", "HT-011"], "B"),
         ("OMEGA", ["VP-019"], "B"),
         ("Danfoss", ["EA-009"], "C"),
         (None, ["HT-011"], "B")],
}

# 명부에 분류가 비어 있는 메이커의 분류 제안 — 공개 정보 기준 추정이다. 확정되면
# makers.category_ids 에 옮겨 적고 여기서 지운다(카탈로그는 명부 값을 먼저 쓴다).
PROPOSED_TAGS = {
    "Caterpillar": ["EN", "EN-033"],
    "Chongqing Hongjiang Machinery": ["EN-003", "EN-031"],
    "Coffin World Water Systems": ["AU-001"],
    "CSSC Engine(CSE)": ["EN"],
    "DK-LOK": ["VP-001", "VP-017"],
    "DMV (Dalian)": ["VP"],
    "DONG EUN VALVE": ["VP"],
    "DONGHWA ENTEC": ["HT-001", "HT-002"],
    "Gadelius Marine": ["HT-009"],
    "Hanshin": ["EN"],
    "HANYANG VALVE": ["VP"],
    "HI AIR KOREA": ["HT-011", "HT-012"],
    "HITACHI Zosen Marine Engine": ["EN"],
    "Hübner": ["EA-008"],
    "IMO Pump": ["AU-002"],
    "Ingersoll-Rand Machinery (Shanghai)": ["AU-006"],
    "JOKWANG ILI": ["VP-002", "VP-011"],
    "KEYSTONE": ["VP-002"],
    "KOREA KEYSTON VALVE": ["VP-002"],
    "Kongsberg": ["EA-007"],
    "KSB": ["AU-001", "VP-002"],
    "Liebherr": ["DK-004"],
    "MESON": ["EV-001", "EV-006"],
    "Mitsubishi": ["AU-011", "EN-022"],
    "Mitsubishi Kakoki Kaisha": ["AU-011"],
    "Miura": ["HT-006", "HT-007"],
    "Naniwa": ["AU-001"],
    "NEWAY": ["VP"],
    "PK VALVE": ["VP"],
    "Rolls-Royce Marine": ["DK-009", "EN-035", "EN-038"],
    "S&S VALVE": ["VP"],
    "SAACKE": ["HT-006"],
    "SCANA": ["EN-035", "EN-036"],
    "Schneider Electric": ["EA-002", "EA-005", "EA-009"],
    "SEJIN VALVE": ["VP"],
    "Sulzer": ["EN", "AU-001"],
    "Suntec": ["AU-002", "HT-006"],
    "Taiko Kikai": ["AU-001", "AU-002"],
    "Weishaupt": ["HT-006"],
    "Westfalia Separator": ["AU-011", "AU-012"],
    "Wilo": ["AU-001"],
    "WONKWANG VALVE": ["VP"],
    "Wuhan Marine Machinery Plant": ["DK-001", "DK-004"],
    "Yuchai Marine Power": ["EN", "EN-033"],
}

# 기술 서비스 실적(TS). 딜 id → 고객용 한 줄 설명. 등급은 딜 근거에서 계산한다.
SERVICE_RECORDS = {
    1:  "Main engine cylinder liner / jacket O-ring renewal — onboard attendance",
    35: "Deck crane electrical troubleshooting & cable renewal — attendance abroad (Zhoushan, China)",
    18: "Auxiliary engine main bearing & connecting rod inspection",
    28: "Hose handling crane heaving fault inspection",
    32: "Crane hydraulic cylinder overhaul — gas-free, removal, workshop overhaul, reinstallation",
    24: "Fixed gas detection system (BWTS) fault repair",
    54: "ODME inspection & repair",
}
